#!/usr/bin/env sh

#yabai -m config debug_output on
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"


yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             default
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

yabai -m config layout                       bsp
yabai -m config top_padding                  20
yabai -m config bottom_padding               20
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   10
yabai -m config external_bar                 all:20:0

yabai -m config window_border                on
yabai -m config window_border_width           5
yabai -m config active_window_border_color    0xff9dd274
yabai -m config normal_window_border_color    0xff555555

# Do not manage some apps which are not resizable
yabai -m rule --add app="^(LuLu|Calculator|VLC|System Preferences|Photo Booth|Archive Utility|Python|Finder|Raycast|App Store|Activity Monitor|Dictionary|Software Update|System Information|About This Mac|Digital Colour Meter|)$" manage=off
# Rules
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off

yabai_create_spaces="Code Web Mail Misc."

## Create spaces and label them
i=0; for name in ${yabai_create_spaces}; do
  i=$((i+1))
  yabai -m space ${i} --label ${name}
  
  if [ ${i} -lt ${yabai_create_spaces_count} ]; then
    yabai -m space --create
  fi
done

## Sticky Windows
yabai -m rule --add app="^Bitwarden$" sticky=on
yabai -m rule --add app="^ProtonVPN$" sticky=on


## Screen 1 (Code)
space=1
yabai -m rule --add app="^VSCodium$" space="${space}"
yabai -m rule --add app="^Xcode$" space="${space}"

## Screen 2 (Web)
space=2
yabai -m rule --add app="^Firefox$" space="${space}"

## Screen 3 (Mail)
space=3
yabai -m rule --add app="^Mail$" space="${space}"
yabai -m rule --add app="^ProtonMail Bridge$" space="${space}"

## Screen 4 (Misc.)
space=4
yabai -m rule --add app="^Signal$" space="${space}"

echo "yabai configuration loaded.."
